"""Trigger text for each Perl rule - used by test_rules_per_rule.py."""

# Rule name -> LaTeX fragment that should trigger the rule.
# For simple_rule, name usually equals trigger. Array rules need explicit triggers.
# Keys match rule[0] from generate_error_types().

# Import for rules whose names are regex-like (must match rule[0] exactly)
from lyxgc.tokenizer import LATEX_BS

TRIGGERS_EN = {
    # SimpleRules - use name as trigger (most)
    "we that": "we that",
    "spelt correctly": "spelt correctly",
    "into to": "into to",
    "never-the-less": "never-the-less",
    "the automata": "the automata",
    "but and": "but and",
    "in terms on the": "in terms on the",
    "in terms if the": "in terms if the",
    "psuedo": "psuedo",
    "visa-versa": "visa-versa",
    "visa versa": "visa versa",
    "that the exists": "that the exists",
    "our selves": "our selves",
    "number of reason": "number of reason",
    "the both": "the both",
    "we will shown": "we will shown",
    "this important because": "this important because",
    "not contains": "not contains",
    "we interested": "we interested",
    "of he": "of he",
    "is are": "is are",
    "the in": "the in",
    "This demonstrations": "This demonstrations",
    "will defined": "will defined",
    "some a": "some a",
    "a some": "a some",
    "satisfiable in B?CTL-structure": "satisfiable in BCTL-structure",
    "Hintakka": "Hintakka",
    "as assume": "as assume",
    "eDecendants": "eDecendants",
    "way point": "way point",
    "of there": "of there",
    "is grows": "is grows",
    "non trivial": "non trivial",
    "million of lines": "million of lines",
    "that this provides use with a": "that this provides use with a",
    "Now that we now that each": "Now that we now that each",
    "over view": "over view",
    "an of": "an of",
    "the following a": "the following a",
    "a conservative extensions": "a conservative extensions",
    "be use to": "be use to",
    "enquire as how": "enquire as how",
    "model checker CTL": "model checker CTL",
    "can efficient": "can efficient",
    "polynomial model checking": "polynomial model checking",
    "greater motivation": "greater motivation",
    "may first appear": "may first appear",
    "comparision to": "comparision to",
    "comparisions to": "comparisions to",
    "polices": "polices",
    "alteration": "alteration",
    "a considerable research": "a considerable research",
    "avoid stay": "avoid stay",
    "reasonably to ask": "reasonably to ask",
    "would beneficial": "would beneficial",
    "with be": "with be",
    "a valid in": "a valid in",
    "that occur which": "that occur which",
    "more tractable": "more tractable",
    "the deviation event": "the deviation event",
    "is no sufficent": "is no sufficent",
    "verify that is satisfies": "verify that is satisfies",
    "provides us with we have": "provides us with we have",
    "sch that": "sch that",
    "presented at": "presented at",
    " (?<!in.the.)tableau are": "tableau are",
    "formally reason these": "formally reason these",
    "to presented": "to presented",
    "path-quantifies": "path-quantifies",
    "path quantifies": "path quantifies",
    "on of": "on of",
    "must exists": "must exists",
    "see e.g.": "see e.g.",
    "world formula(?:[es])?": "world formula",
    "For example(?![,:])": "For example",
    "there no": "there no",
    "show that is [^\\s]+ satisfiable": "show that is x satisfiable",
    "a special atoms": "a special atoms",
    # Array rules
    "Two Pretty": r"Lemma \prettyref{cha:foo}",
    "Either ... and": "Either X and Y",
    "Plural Mismatch (as)": "s as a",
    "pspace-compLete": "PSPACE-compete",
    "Bad plural": "A CTL-structures",
    "A plural": "a biases",
    "Empty mathblock": "$$ $$",
    "Formula in place of fullpath.": r"$\phi \forces$",
    "Mixing a and beta.": r"aU\beta",
    "Thus twice": "Thus x. Thus y.",
    "Macro without {}.": "x\\fooCTLbar ",
    "Second word in sentence is captalised.": ". foo Bar",
    "no full stop after cite that ends paragraph": r"x \cite{key}" + "\n\n",
    "No space after cite": r"\cite{key}x",
    "No space before cite": r"x\cite{key}",
    "While while": "While x while y",
    "Plural of acronym ending is S requires apostrophy between the `S'": "AGSs",
    "Underline starts too early": r"\uline{ ",
    "Underline ends too late": r"\uline{x }",
    "Space before foot-note": r" \footnote{",
    "Period/Comma after foot-note": r"\footnote{x}.",
    "Singular both": "Both x.",
    "Double [": "[[",
    "Double Punctuation": ", .",
    "The [logic]": "the CTL :",
    "Use of implies for forward direction in proof": r"(\implies)",
    "Personal Rule; RoCTL{*}": r"RoCTL. {{*}}. ",
    "Personal Rule; RoCTL missing *": " RoCTL ",
    "No space after reference": r"\ref{lem:x}y",
    "Single char": " x ",
    "A likely as": "A likely as",
    "To modelled": "to modelled",
    "A formulae": r"a formulae",
    "Personal Rule, Robustly operated": "Robustly operated",
    "it every": "it every",
    "A we": "A we",
    "Personal Rule: valdities": "validitiy",
    "blow up": "blow up",
    "it self": "it self",
    "Personal Rule: ROCTL": "ROCTL",
    "is was": "is was",
    "Capital without preceeding fullstop": "foo Bar",
    "Capital 'In' without preceeding fullstop": "foo In",
    "In Practise": "in practise",
    "Empty Begin/End Block": r"\begin{lem}\end{lem}",
    "it thus a": "it thus a",
    "Personal rule: in A": r"in $A$",
    "Proof starting not on newline": r"x\begin{proof}",
    "No space between text and reference": r"x\prettyref{sec:a}",
    ". .": ". .",
    "in term of": "in term of",
    "From of": "From of",
    "Will is": "Will is",
    "The a": "The a",
    "Personal rule: forall_": "forall_",
    "Personal rule: missing -": "Pair RoCTL",
    "Were [math]": r"were $x$",
    "Also and": "Also and",
    "Personal rule: found failure free in place of 'failure-free'": "failure free",
    "Personal rule: CTL structures": "CTL struct",
    "Personal rule: operator name without capital": "obligatory operator",
    "with by": "with by",
    "with in": "with in",
    "Where as": "Where as",
    "space between cite and punctuation": r"\cite{key} ,",
    "there exist phi": r"there exist $\phi:\psi$",
    "formula it": "formula it",
    ".Capital": ".X",
    ".word": ".foo ",
    "Exists as s..": "Exists as s",
    "Space between mathblock and punctuation": r"$x$ ,",
    "Inapproriate capital after mathblock": r"x $a$ Bar",
    "Equals outside mathblock": r"$a$ = $b$",
    "a that": "a That",
    "the there": "the there",
    "there where": "there where",
    "with where": "with where",
    "[Tt]he proofs that converge": "the proofs that converge",
    "[Aa]nd a presented": "And a presented",
    "Cause change the": "Cause change the",
    "In place voter": "In place voter",
    "We allow only {to}? require": "We allow only require",
    "Programs can be computed": "Programs can be computed",
    "To be converge": "To be converge",
    "Factions?": "factions",
    "hEIrarchy": "heirarchy",
    "exponential blow up": "exponential blow up",
    "be behave": "be behave",
    "Anyway of": "anyway of",
    "been replace[d]": "been replace",
    "The [noun] may": "The may",
    "It involve[s]": "it involve",
    "At leas[e] as": "At lease as",
    "Use of An where A is expected": "An pear",
    "Use of A where An is expected": "a apple",
    "Use of the and 's": "The Bob's",
    "Sentance must begin with capital letter": ". foo",
    "No space before math block": r"x$x$",
    "No space before citation": r"x\cite{key}",
    "Capital following comma": ", Bar",
    "Inappropriate capital": "x It",
    "Footnote is not fullstop": r"x \footnote{x} Bar",
    "No space after math block": r"$x$y",
    "No space before macro": r"x\term{foo}",
    "No space after macro": r"\term{foo}x",
    "A used for plural": "a sequences",
    "Use of : in math-mode": r"$f: x$",
    "less that": "less that",
    "Ugly fraction": "1/2",
    "Too many zeros without a comma": "0000",
    "Split word": "with out",
    "Duplicated Words": "foo foo",
    "Duplicated Words (broken)": "foo foo",
    "Use of I.e.": "I.e. foo",
    'Use of "we could".': "we could",
    "No space between sentances": "x.Y",
    "Missing hyphen after math block": r"$x$ multinomial",
    "Paragraph should end in fullstop": "x\n\n",
    "Paragraph should start with capital": "\n\nfoo",
    "Paragraph starts with fullstop?": "\n\n.",
    "Place punctuation outside mathmode": r"$x,$",
    "Place . after *": "CTL.*",
    "Double dot": ". .",
    "Remove space before punctuation": "word ,",
    "Remove space before punctuation[2]": "word '",
    "Index entries should start with capital letters": r"\index{foo}",
    "Perhaps you mean `is that'": "it that",
    "You should use Var()": r"\Vari[",
    "Amiguous Terminology": "and but",
    "Use of pretty ref with out prefix": r"\prettyref{sec:x}",
    "NOT IS is odd.": "not is",
    "Lemma label without 'lem:'": r"\begin{lem} \label{x}",
    "Corollary label without 'cor:'": r"\begin{cor} \label{x}",
    "Theorem label without 'thm:'": r"\begin{thm} \label{x}",
    "Lack of Lemma prefix": r"foo \ref{lem:x}",
    "Lack of Corollary prefix": r"foo \ref{cor:x}",
    "Lack of Theorem prefix": r"foo \ref{thm:x}",
    "Lack of Definition prefix": r"foo \ref{def:x}",
    "Use of lowercase reference": r"lemma \ref",
    "lemma/theorem occurs before prettyref": r"lemma \prettyref",
    "Empty Footnote": r"\footnote{}",
    "Attempt to Pluralize a name": "Turings",
    "Unraised 'c' in 'Mc'": "McDonald",
    "Section ending with '.'": r"\section{foo.}",
    "Forge(t) to": "forge to",
    "May the": "We may the",
    "$ discuss": r"$x$ Discuss",
    "He vs the": "he path",
    "The we": "The we",
    "Use of however without comma": "; However",
    "Use of Joining word": "; Hence",
    "Is be": "Is be",
    "It represent": "it represent",
    "Space before punctuation": r"$x$ ,",
    "Forces what?": r"$a$(\forces",
    "Be is": "be is",
    "Inappropriate Title Capital": "foo The bar",
    "Personal rule - I probably mean Spatial": "pacial",
    "Personal rule - I probably through": "path though",
    "Personal rule - structure OR CTL-model": "structure CTL-model",
    "Personal rule - I probably mean abbreviation": "shorthand",
    "Personal rule - Replace log with ln": r"$\log$",
    "We call ... is a": "we call x is a",
    "A One": "a one",
    "Can be express": "can be express",
    "This paper(')s": "This papers",
    "The never": "The never",
    "The at": "The at",
    "Personal rule - moral": "moral",
    "We expect": "We expect",
    "Axiom[i->a]tisation": "axiomitization",
    "Classic[al] Logic": "Classic Logic",
    "Space before )": r"$x$ )",
    "Converge [to] the": "converge the",
    "use or used": "use x is used",
    "Lonely End Proof": "\n\n" + r"\end{proof}",
    "Paragraph following COLON": ": \n\n" + r"\begin{align}x\end{align}",
    "Personal rule - remove the i": "Automation",
    "no full stop at end of definition": r"x \end{definition}",
    "no full stop at end of .*": r"x \end{equation}",
    # Rules that fire alongside others (no isolation needed)
    "A plural": "a axes",
    "Duplicated Words (broken)": "foo bar foo",
    # Rules with regex-like names (key must match rule[0] exactly)
    r"^.\s+[A-Z]": "  B",
    r"^.\\s+[A-Z]": ". .",
    **{LATEX_BS + r"textquotedbl\{[}]": r"\textquotedbl{}"},
}

# Rules whose names are not suitable as triggers (regex-like, etc.) - use explicit
# For names that ARE the trigger, we default to name in the test.


# French triggers - rules from chktex_fr.pl
TRIGGERS_FR = {
    "Empty mathblock": "$$ $$",
    "Macro sans {}.": "x\\fooCTLbar ",
    "Le second mot de la phrase commence par une majuscule.": ". foo Bar",
    "pas de point d'arrêt après une citation en fin de paragraphe": r"x \cite{key}" + "\n\n",
    "Espace après citation": r"\cite{key}x",
    "Espace avant citation": r"x\cite{key}",
    "Le soulignement commence trop tôt": r"\uline{ ",
    "Le soulignement fini trop loin": r"\uline{x }",
    "Espace avant note de bas de page": r" \footnote{",
    "Point/Virgule après note de bas de page": r"\footnote{x}.",
    "Ponctuation double": ", .",
    "Utilisation d'une implication dans une preuve": r"(\implies)",
    "Pas d'espace après un référencement": r"\ref{x}y",
    "Un seul caractère": " x ",
    "Majuscule au milieu d'une phrase": "foo Bar",
    "Block Begin/End vide": r"\begin{lem}\end{lem}",
    "La preuve ne démarre pas sur une nouvelle ligne": r"x\begin{proof}",
    "Pas d'espace entre une référence et le texte à sa gauche": r"x\prettyref{sec:a}",
    "Pas d'espace entre une référence et le texte à sa droite": r"\prettyref{sec:a}",
    "Trop de points": ". .",
    "espace entre la citation et la ponctuation": r"\cite{key} ,",
    "Espace manquant entre point et majuscule": ".X",
    "Espace manquant entre point et mot": ".foo ",
    "Mauvaise usage des guillements": r"\textquotedbl{}",
    "Espace entre block de math et ponctuation": r"$x$ ,",
    "Majuscule après block de math": r"x $a$ Bar",
    "Signe égal '=' en dehors d'un block de math": r"$a$ = $b$",
    "Pas d'espace avant un block de math": r"x$x$",
    "Pas d'espace avant une citation": r"x\cite{key}",
    "Majuscule après virgule": ", Bar",
    "Majuscule inattendue": "x Bar",
    "La note de bas de page manque un point": r"x \footnote{x} Bar",
    "Pas d'espace après block de math": r"$x$y",
    "Pas d'espace avant une macro": r"x\term{foo}",
    "Pas d'espace après une macro": r"\term{foo}x",
    "Un(e) utilisé avec un pluriel": "Une sequences",
    "Utilisation de : dans le mode math": r"$f: x$",
    "Fraction disgracieuse": "1/2",
    "Trop de zéros sans séparateur": "0000",
    "Mot dupliqué": "foo foo",
    "Un paragraphe doit se terminer par un point": "x\n\n",
    "Un paragraphe doit commencer par une majuscule": "\n\nfoo",
    "Paragraphe démarrant par un point ?": "\n\n.",
    "Ponctuation à l'intérieur du mode math": r"$x,$",
    "Deux points": ". .",
    "Ajouter une espace avant ponctuation": "mot;",
    "Supprimer une espace avant punctuation": "mot '",
    "Les entrées de l'index commencent par une majuscule": r"\index{foo}",
    "Vous devriez utiliser Var()": r"\Vari[",
    "Utilisation de prettyref sans préfixe": r"\prettyref{sec:x}",
    "Label «Lemme» sans «lem:»": r"\begin{lem} \label{x}",
    "Label «Corollaire» sans «cor:»": r"\begin{cor} \label{x}",
    "Label «Théorème» sans «thm:»": r"\begin{thm} \label{x}",
    "Préfixe Lemme manquant": r"foo \ref{lem:x}",
    "Préfixe Corollaire maquant": r"foo \ref{cor:x}",
    "Préfixe Théorème maquant": r"foo \ref{thm:x}",
    "Référence en minuscule": r"lemme \ref",
    "lemme/théorème apparaît avant prettyref": r"lemma \prettyref{sec}",
    "Note de bas de page vide": r"\footnote{}",
    "Section se terminant par un '.'": r"\section{foo.}",
    "Pas d'espace avant ponctuation": r"$x$,",
    "Espace avant «)»": r"$x$ )",
    "Fin de preuve sans début": "\n\n" + r"\end{proof}",
    "pas de point à la fin de la définition": r"x \end{definition}",
    "pas de point à la fin de .*": r"x \end{equation}",
}
